version: '3.8'

services:
    # zookeeper:
    #     image: confluentinc/cp-zookeeper:latest
    #     environment:
    #         ZOOKEEPER_CLIENT_PORT: 2181
    #     ports:
    #         - '2181:2181'

    # kafka:
    #     image: confluentinc/cp-kafka:latest
    #     depends_on:
    #         - zookeeper
    #     ports:
    #         - '9092:9092'
    #     environment:
    #         KAFKA_BROKER_ID: 1
    #         KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    #         KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    #         KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    #         KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    kafka:
      image: confluentinc/cp-kafka:latest
      ports:
          - '9092:9092'
      environment:
          KAFKA_BROKER_ID: 1
          KAFKA_PROCESS_ROLES: broker,controller
          KAFKA_NODE_ID: 1
          KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
          KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
          KAFKA_LOG_DIRS: /var/lib/kafka/data
          CLUSTER_ID: test-kafka-cluster
