version: '3.8'

services:
    user-service:
        restart: always
        deploy:
            resources:
                limits:
                    memory: 512M
                    cpus: '0.5'
        logging:
            driver: 'json-file'
            options:
                max-size: '10m'
                max-file: '3'

    api-gateway:
        restart: always
        deploy:
            resources:
                limits:
                    memory: 512M
                    cpus: '0.5'
        logging:
            driver: 'json-file'
            options:
                max-size: '10m'
                max-file: '3'
