version: '3.8'

services:
    user-service:
        build:
            context: ./user-service
            dockerfile: Dockerfile
        container_name: user-service
        ports:
            - '50051:50051'
        networks:
            - grpc-network
        environment:
            - PORT=50051
        # healthcheck:
        #     test: ['CMD', 'grpc_health_probe', '-addr=localhost:50051']
        #     interval: 30s
        #     timeout: 10s
        #     retries: 3
        #     start_period: 40s

    api-gateway:
        build:
            context: ./api-gateway
            dockerfile: Dockerfile
        container_name: api-gateway
        ports:
            - '8080:8080'
        networks:
            - grpc-network
        environment:
            - PORT=8080
            - USER_SERVICE_ADDR=user-service:50051
        depends_on:
            - user-service
        #     user-service:
        #         condition: service_healthy
        # healthcheck:
        #     test:
        #         [
        #             'CMD',
        #             'wget',
        #             '--no-verbose',
        #             '--tries=1',
        #             '--spider',
        #             'http://localhost:8080/health',
        #         ]
        #     interval: 30s
        #     timeout: 10s
        #     retries: 3
        #     start_period: 40s

networks:
    grpc-network:
        driver: bridge
